variables:
  TERM: linux
  MINGW32_BOOST_VERSION: 1.81.0-7
  MINGW64_BOOST_VERSION: 1.81.0-7
  WGET_OPTIONS: '--no-verbose --no-use-server-timestamps --retry-connrefused --retry-on-host-error'

build_linux_x86_64:
  stage: build
  script:
    - autoreconf -si
    - ./configure --host=x86_64-linux-gnu
    - make -j$(nproc)
  artifacts:
    paths:
      - src/dynare-preprocessor

build_linux_arm64:
  stage: build
  script:
    - autoreconf -si
    - ./configure --host=aarch64-linux-gnu
    - make -j$(nproc)
  artifacts:
    paths:
      - src/dynare-preprocessor

build_windows_x86_64:
  stage: build
  script:
    - mkdir -p tarballs
    - '[[ -f tarballs/mingw-w64-x86_64-boost-$MINGW64_BOOST_VERSION-any.pkg.tar.zst ]] || wget $WGET_OPTIONS -P tarballs http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-boost-$MINGW64_BOOST_VERSION-any.pkg.tar.zst'
    - mkdir -p deps
    - tar xf tarballs/mingw-w64-x86_64-boost-$MINGW64_BOOST_VERSION-any.pkg.tar.zst --directory deps
    - autoreconf -si
    - ./configure --host=x86_64-w64-mingw32 --with-boost=$(pwd)/deps/mingw64/include
    - make -j$(nproc)
  cache:
    # This cache is shared between all branches, to save space
    key: $CI_JOB_NAME
    paths:
      - tarballs/
  artifacts:
    paths:
      - src/dynare-preprocessor.exe

build_macos_x86_64:
  stage: build
  tags:
    - macOS
  script:
    - autoreconf -si
    - arch -x86_64 ./configure CC=gcc-13 CXX=g++-13 LEX=/usr/local/opt/flex/bin/flex YACC=/usr/local/opt/bison/bin/bison
    - arch -x86_64 make -j$(sysctl -n hw.ncpu)
  artifacts:
    paths:
      - src/dynare-preprocessor
