option('build_library', type: 'feature', value: 'auto', description: 'Build Python extension module')
option('build_cli', type: 'feature', value: 'auto', description: 'Build standalone CLI executable')
option('build_doc', type: 'boolean', value: false, description: 'Build and install documentation')

