[tool.poetry]
name = "preproc"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pip = "^23.3.1"


[build-system]
build-backend = "mesonpy"
requires = [
	"pybind11",
	"meson-python",
	"meson",
	"flex"
]
